services:
    mysql:
        image: mysql:8
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQLDATABASE}
            MYSQL_USER: ${MYSQLUSER}
            MYSQL_PASSWORD: ${MYSQLPASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    auth-service:
        build: .
        container_name: auth-container
        environment:
            DB_HOST: ${MYSQLHOST}
            DB_PORT: ${MYSQLPORT}
            DB_NAME: ${MYSQLDATABASE}
            DB_USER: ${MYSQLUSER}
            DB_PASS: ${MYSQLPASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            JWT_EXPIRATION: ${JWT_EXPIRATION}
        ports:
            - "8083:8080"
        depends_on:
            - mysql

volumes:
    mysql-data:
